### ISSUE TITLE
Missing files in PyPI package

### ISSUE THREAD

**Issue by jluttine** [moggers87/lmtpd#5]
test_lmtp file is not included in PyPI release tarball. Could it be added so one could use it as a source when packaging for distros? For now, I'll use the GitHub release tarball because that contains it.

**Comment by moggers87** [comment]
Can do.

The PyPI package is also missing the two license files, I'd somehow missed that before.

**Comment by moggers87** [comment]
I'll release this once I've fixed #4 and #3

**Comment by moggers87** [comment]
@jluttine this has now been released on PyPI as version 6.0.0
