### ISSUE TITLE
Multiple responses, how?

### ISSUE THREAD

**Issue by vanrein** [moggers87/lmtpd#9]
From reading the pydoc on lmtpd, I cannot work out how to return a single reply for every recipient.  Moreover, it is strange that the last one should be explicitly returned, as `None` would also have a response that would apply to that last recipient.

It would make sense to me to return a list as long as the list of `RCPT TO` addresses; it would also make sense if a separate `250 Ok` was sent for each of these when `None` was returned.  But I cannot work this out from the documentation.

Furthermore, an empty list of `RCPT TO` addresses should return `503`, which is a deviation from SMTP.  Has this been taken care of, or is it the subclass's responsibility?

Finally, a remark might be useful that the module really completely locks out unless it is sent the CR-LF line endings.  It is absolutely not forgiving (and `nc -C` is enough to resolve that, but it helps to know why it freezes).

Could you update the documentation please, and if needed, the code as well, to deviate from SMTP where LMTP needs it?

**Comment by moggers87** [comment]
> From reading the pydoc on lmtpd, I cannot work out how to return a single reply for every recipient.

For each recipient, `process_message` is called. See here: https://github.com/moggers87/lmtpd/blob/master/lmtpd/__init__.py#L93

> Moreover, it is strange that the last one should be explicitly returned, as `None` would also have a response that would apply to that last recipient.

I'm not sure what this means.

> It would make sense to me to return a list as long as the list of `RCPT TO` addresses; it would also make sense if a separate `250 Ok` was sent for each of these when `None` was returned. But I cannot work this out from the documentation.

That sounds awful!

> 
> Furthermore, an empty list of `RCPT TO` addresses should return `503`, which is a deviation from SMTP. Has this been taken care of, or is it the subclass's responsibility?

To the best of my knowledge that is not a deviation from SMTP. If the client issues `DATA` before a valid `RCPT TO` has been given, then a `503` response is given.

> Finally, a remark might be useful that the module really completely locks out unless it is sent the CR-LF line endings. It is absolutely not forgiving (and `nc -C` is enough to resolve that, but it helps to know why it freezes).

Could you tell me which RFC says you can use anything other than `crlf` end-of-lines? As far as I know, `crlf` is the standard.

> Could you update the documentation please, and if needed, the code as well, to deviate from SMTP where LMTP needs it?

You've mentioned documentation a couple of times, but I'm not aware of any. Could you tell me what documentation you've been reading?

**Comment by vanrein** [comment]
Hi Matt,
Matt Molyneaux wrote:
>> From reading the pydoc on lmtpd, I cannot work out how to return a single reply for every recipient.
>
> For each recipient, `process_message` is called. See here: https://github.com/moggers87/lmtpd/blob/master/lmtpd/__init__.py#L93

That is a clever idea for LMTP.  Did I overlook it in the docs?  I found descriptions of an array of recipients, which in this case becomes an array of single characters ;-)  This stems from smtpd of course, but the documentation says lmtpd is the same.

This conceptual simplicity comes at a price, I believe --I need to do recompute the DKIM validator and further processing for each recipient separately-- unless there is a way to share the common state of the message submission.  If this is just what the lmtpd process instance does, it may be a useful documentation hint to add.

>> Moreover, it is strange that the last one should be explicitly returned, as `None` would also have a response that would apply to that last recipient.
>
> I'm not sure what this means.

It does not apply after what you said above.

I was assuming I'd get, say, 3 recipients.  Then the last one is responded to by the return from the routine and the first and second needed different treatment.

>> It would make sense to me to return a list as long as the list of `RCPT TO` addresses; it would also make sense if a separate `250 Ok` was sent for each of these when `None` was returned. But I cannot work this out from the documentation.
>
> That sounds awful!

What you did is indeed more logical.  My compliments on that decision :)

>> Furthermore, an empty list of `RCPT TO` addresses should return `503`, which is a deviation from SMTP. Has this been taken care of, or is it the subclass's responsibility?
>
> To the best of my knowledge that is not a deviation from SMTP. If the client issues `DATA` before a valid `RCPT TO` has been given, then a `503` response is given.

OK, might be.  I took this from the RFC on LMTP which said so.  Anyhow, as I don't get an array that might be empty there's no way I could do this so you have to :-D

>> Finally, a remark might be useful that the module really completely locks out unless it is sent the CR-LF line endings. It is absolutely not forgiving (and `nc -C` is enough to resolve that, but it helps to know why it freezes).
>
> Could you tell me which RFC says you can use anything other than `crlf` end-of-lines? As far as I know, `crlf` is the standard.

Yes I know.  But I've also never come across SMTP daemons that enforce it.  LMTP was a bit of a surprise and it threw me back initially.  Just a hudle that can be taken once it is clear, but I thought it might help to mention.

>> Could you update the documentation please, and if needed, the code as well, to deviate from SMTP where LMTP needs it?
>
> You've mentioned documentation a couple of times, but I'm not aware of any. Could you tell me what documentation you've been reading?

The pydoc on ltmpd and the RFC on LMTP.

I got lmtpd going for me, with the exception of the efficiency of shared state on a shared message, so I'm rolling now.  Nice little package, once you get it going.

-Rick

**Comment by moggers87** [comment]
OK, I think I've answered all the questions I can.

Closing this issue now.
